baseURL = 'https://notsuoholi.github.io/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = "Oli's Workshop"
theme = "hugo-blog-awesome"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

############################## English language ################################
[Languages.en-us]
  languageName = "English"
  languageCode = "en-us"
  contentDir = "content/"
  weight = 1

  [Languages.en-us.menu]
  [[Languages.en-us.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-us.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/pages/about/'
    weight = 20
  [[Languages.en-us.menu.main]]
    pageRef="background"
    name = 'Background'
    url = '/pages/background/'
    weight = 25
  [[Languages.en-us.menu.main]]
    pageRef="reliability"
    name = 'Building Reliability'
    url = '/pages/reliability'
    weight = 30
  [[Languages.en-us.menu.main]]
    pageRef="srevsdevops"
    name = 'SRE vs DevOps'
    url = '/pages/srevsdevops/'
    weight = 35

[Languages.en-us.params]
  sitename = "Oli's Workshop"
  defaultColor = "auto" # set color mode: dark, light, auto
  # You can take a look at layouts/index.html for more information.
  description = "Minimal Hugo blog theme with light and dark mode support"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  # dateFormat = "02 Jan 2006"
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .

[Languages.en-us.params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Oli's Workshop"
  name = "Oli Blaine"
  description = "This is where I host my personal projects, blog posts, and stuff that interests me in general. Feel free to take a look around."

# Allow to override webmanifest options
[Languages.en-us.params.webmanifest]
  name = "olis-workshop" # will use "params.sitename" or "title" by default
  short_name = "olis-workshop" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"


##### Additional Params #####
[[params.socialIcons]]
name = "github"
url = "https://github.com/notsuoholi"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/oliblaine"

[params]
  goToTop = true